<?php

namespace AppBundle\Repository;

use AppBundle\Creator\OrderCreator;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Given an array of values, pass the variables into a creator and save the resulting object
     *
     * @param $values
     * @return bool|object
     */
    public function createNewOrder($values)
    {
        try {
            $creator = new OrderCreator();

            $order = $creator->setValues($values)->create();

            $this->getEntityManager()->persist($order);

            $this->getEntityManager()->flush();
        } catch (\Exception $e) {
            return false;
        }

        return $order;
    }
}
